#!/usr/bin/env python3
"""Create a shared company workspace skeleton for ClawTasker."""
from __future__ import annotations

import argparse
from pathlib import Path

BLUEPRINT = [
    "company/control/directives",
    "company/control/org",
    "company/control/calendar",
    "company/shared-playbooks",
    "company/projects/atlas-core/tasks",
    "company/projects/atlas-core/src",
    "company/projects/atlas-core/docs",
    "company/projects/atlas-core/qa",
    "company/projects/atlas-core/artifacts",
    "company/projects/market-radar/research",
    "company/projects/market-radar/publishing",
    "company/projects/market-radar/artifacts",
    "company/projects/ceo-console/web",
    "company/projects/ceo-console/docs",
    "company/projects/ceo-console/qa",
    "company/projects/ceo-console/artifacts",
]

PROJECT_NOTES = {
    "atlas-core": "Shared automation and integration backbone.",
    "market-radar": "Briefings, scans, and distribution workflows.",
    "ceo-console": "ClawTasker product UI, docs, and releases.",
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("destination", help="Path where the company workspace should be created")
    args = parser.parse_args()

    root = Path(args.destination).expanduser().resolve()
    for relative in BLUEPRINT:
        path = root / relative
        path.mkdir(parents=True, exist_ok=True)
        keep = path / ".gitkeep"
        keep.touch(exist_ok=True)

    for project, note in PROJECT_NOTES.items():
        manifest = root / "company" / "projects" / project / ".clawtasker-project.md"
        manifest.write_text(f"# {project}\n\n{note}\n", encoding="utf-8")

    readme = root / "company" / "README.md"
    if not readme.exists():
        readme.write_text(
            "# Company workspace\n\nGenerated by ClawTasker. Use one shared repo per project, branch per task, and validation before merge.\n",
            encoding="utf-8",
        )

    print(f"ClawTasker workspace created at {root / 'company'}")


if __name__ == "__main__":
    main()
